### ISSUE TITLE
Developing for CUDA 8.0

### ISSUE THREAD

**Issue by sabamiso1** [andyneff/cuda-waste#17]
Would you develop for CUDA 8.0 version of cuda-waste?
I tried to compile by myself, but its codes seem to depend on cuda 4.

I want to use this program for MATLAB to use Deep Learning.
https://www.mathworks.com/help/vision/examples/image-category-classification-using-deep-learning.html?requestedDomain=www.mathworks.com&nocookie=true

MATLAB needs NVIDIA GPU, but I don't have it now.
So, I think this program can be used for it, but CUDA version more than 7.5 is required.

**Comment by andyneff** [comment]
@sabamiso1 Unfortunately, I am not currently maintaining this repo, I was just trying to get it hosted on github. If you have any PRs, I'll gladly merge them in.
