### ISSUE TITLE
How your PTX parser compares to PTX parser of Ocelot?

### ISSUE THREAD

**Issue by dmikushin** [andyneff/cuda-waste#18]
Hi @andyneff , could you please kindly help me to compare two PTX parsers: [yours](https://github.com/andyneff/cuda-waste/blob/master/ptxp/Ptx.g) and the one from the [Ocelot project](https://github.com/gpuocelot/gpuocelot/blob/master/ocelot/src/parser/ptxgrammar.yy). I'm not an expert at all, but can you confirm that your parser is more feature complete, although both are targeting very old PTX standard? Do you know of any other opensource PTX parsers being developed?

**Comment by andyneff** [comment]
This is just a fork of a Google Code repo. Unfortunately I don't know anything about how it works.
